apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: {{ .Chart.Name }}
  ports:
    - protocol: {{ .Values.myservice.myprotocol }}
      port: {{ .Values.myservice.port }}
      targetPort: {{ .Values.myimage.containerandtargetPort }}